### ISSUE TITLE
Convert Server to a config entity.

### ISSUE THREAD

**Issue by larowlan** [Laudanum/ldap#10]
Example - http://cgit.drupalcode.org/search_api/tree/src/Entity/Server.php?h=8.x-1.x

The server would contain a setting to store the server type, which would be a plugin ID and the configuration for said server. This is similar to search api's use of backend plugins - see http://cgit.drupalcode.org/search_api/tree/src/Backend?h=8.x-1.x

The fields are defined in the config schema - see http://cgit.drupalcode.org/search_api/tree/config/schema/search_api.server.schema.yml?h=8.x-1.x You can see there they have a reference to the backend plugin Id.

The form for editing is as per the annotation in the config entity definition - sample form - http://cgit.drupalcode.org/search_api/tree/src/Form/ServerForm.php?h=8.x-1.x

**Comment by queenvictoria** [comment]
I think this is done.
