### ISSUE TITLE
What is the purpose of \Drupal\ldap_authentication\LdapAuthentication

### ISSUE THREAD

**Issue by webflo** [Laudanum/ldap#22]
I found ``\Drupal\ldap_authentication\LdapAuthentication`` and have no idea whats the purpose of this class. It inherits the ContentEntityBase class, has comments about the LDAP Server and is in the wrong namespace to be an actual content entity. Its currently not used anywhere.

Should we remove it?

**Comment by webflo** [comment]
The file was introduced in d4072f845efb8ebd54484f868f2c80360af1c87f.

**Comment by queenvictoria** [comment]
So removed!
