### ISSUE TITLE
Can someone push the new 8.x-3.x version to drupal.com and packagist.drupal-composer.org sites?

### ISSUE THREAD

**Issue by jclopez** [Laudanum/ldap#43]
Can someone please push the new 8.x-3.x version to drupal.com and packagist.drupal-composer.org sites?

Thank you for your hard work

**Comment by queenvictoria** [comment]
Done.
https://www.drupal.org/node/2688041

Looks like packagist can't log in with github ID right now. Do you mind if I wait rather than getting yet another account?

**Comment by jclopez** [comment]
It's done, thank you

**Comment by queenvictoria** [comment]
Hey @jclopez if you can see it on packagist please post a link here as this is not it.
https://packagist.org/packages/drupal/ldap

**Comment by jclopez** [comment]
I'm using https://packagist.drupal-composer.org/packages/drupal/ldap
