### ISSUE TITLE
Drupal account for authname=%authname account name=%account_name_attr does not exist and provisioning of Drupal accounts on authentication is not enabled'

### ISSUE THREAD

**Issue by jkeruzec** [Laudanum/ldap#47]
Hello,

Drupal 8 + LDAP module
Open LDAP

I configured LDAP connection with Drupal 8.
Test user is working.
User that is already registered into Drupal works too.

But if I want to log with users only on open ldap side, I have an error even if user is found on Open Ldap (I checked with xDebug).

Error is here, I didn't enable provisionning and I prefer not do to that except if it is mandatory : 

```
 // VI.C.2 Do not provision Drupal account if provisioning disabled.
    if (!$auth_conf->ldapUser->provisionEnabled(LDAP_USER_PROV_DIRECTION_TO_DRUPAL_USER, LDAP_USER_DRUPAL_USER_PROV_ON_AUTHENTICATE)) {
      \Drupal::logger('ldap_authentication')->error('Drupal account for authname=%authname account name=%account_name_attr does not exist and provisioning of Drupal accounts on authentication is not enabled', $watchdog_tokens);
      return;
    }
```

Thank you for your help !

**Comment by jkeruzec** [comment]
I activate Provisionning for the time being. It works and create a basic user into Drupal.

I saw that group management is disable and I can't get my user groups from my LDAP. Do you know if the functionnality is on roadmap ?

Thanks.

**Comment by grahl** [comment]
Please do not use the issue queue but rather the drupal.org one. 

Group assignment to Drupal groups from LDAP groups is generally possible through ldap_authorization in concert with the authorization module.

**Comment by jkeruzec** [comment]
You should remove your link to Github  from https://www.drupal.org/project/ldap page: 

> 8.x-3.x Development Status (updated 16/3/2016)
queenvictoria and his group have moved this forward a great deal. Please try to support them. See https://www.drupal.org/node/2259385 and https://github.com/Laudanum/ldap/issues
